### ISSUE TITLE
Unable to import explorer/sandbox in NextJS

### ISSUE THREAD

**Issue by flyboarder** [apollographql/embeddable-explorer#194]
It seems we are unable to load the embedded packages inside of nextjs.

Steps to reproduce:
1. create nextjs app with `create-next-app`
2. add `@apolllo/sandbox` /or/ `@apollo/explorer` and `graphql` to dependencies
3. attempt to import react element to a page

Fail to import with an error:
```
error - Error: Cannot find module './index.development.js'
Require stack:
- /Users/matt/code/apollo/nextjs-sandbox/sandbox-test/node_modules/@apollo/sandbox/index.cjs
- /Users/matt/code/apollo/nextjs-sandbox/sandbox-test/.next/server/pages/index.js
- /Users/matt/code/apollo/nextjs-sandbox/sandbox-test/node_modules/next/dist/server/require.js
- /Users/matt/code/apollo/nextjs-sandbox/sandbox-test/node_modules/next/dist/server/next-server.js
- /Users/matt/code/apollo/nextjs-sandbox/sandbox-test/node_modules/next/dist/server/next.js
- /Users/matt/code/apollo/nextjs-sandbox/sandbox-test/node_modules/next/dist/server/lib/start-server.js
- /Users/matt/code/apollo/nextjs-sandbox/sandbox-test/node_modules/next/dist/cli/next-dev.js
- /Users/matt/code/apollo/nextjs-sandbox/sandbox-test/node_modules/next/dist/lib/commands.js
- /Users/matt/code/apollo/nextjs-sandbox/sandbox-test/node_modules/next/dist/bin/next
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at mod._resolveFilename (/Users/matt/code/apollo/nextjs-sandbox/sandbox-test/node_modules/next/dist/build/webpack/require-hook.js:27:32)
    at mod._resolveFilename (/Users/matt/code/apollo/nextjs-sandbox/sandbox-test/node_modules/next/dist/build/webpack/require-hook.js:27:32)
    at mod._resolveFilename (/Users/matt/code/apollo/nextjs-sandbox/sandbox-test/node_modules/next/dist/build/webpack/require-hook.js:27:32)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/matt/code/apollo/nextjs-sandbox/sandbox-test/node_modules/@apollo/sandbox/index.cjs:5:20)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/matt/code/apollo/nextjs-sandbox/sandbox-test/node_modules/@apollo/sandbox/index.cjs',
    '/Users/matt/code/apollo/nextjs-sandbox/sandbox-test/.next/server/pages/index.js',
    '/Users/matt/code/apollo/nextjs-sandbox/sandbox-test/node_modules/next/dist/server/require.js',
    '/Users/matt/code/apollo/nextjs-sandbox/sandbox-test/node_modules/next/dist/server/next-server.js',
    '/Users/matt/code/apollo/nextjs-sandbox/sandbox-test/node_modules/next/dist/server/next.js',
    '/Users/matt/code/apollo/nextjs-sandbox/sandbox-test/node_modules/next/dist/server/lib/start-server.js',
    '/Users/matt/code/apollo/nextjs-sandbox/sandbox-test/node_modules/next/dist/cli/next-dev.js',
    '/Users/matt/code/apollo/nextjs-sandbox/sandbox-test/node_modules/next/dist/lib/commands.js',
    '/Users/matt/code/apollo/nextjs-sandbox/sandbox-test/node_modules/next/dist/bin/next'
  ],
  page: '/'
}

```

**Comment by mayakoneval** [comment]
Thanks for the report, this has been fixed in @apollo/explorer 2.0.2 and @apollo/sandbox 1.0.3. 

I am adding tests for Next JS specifically, since this has broken before.
